### ISSUE TITLE
time shift

### ISSUE THREAD

**Issue by sjl6** [Eusebius1920/itmtogpx#2]
When I use ITM_To_GPX.exe on .itm files the resulting .gpx files show a time shift in the `<time>` tag.
On and off 215 trkpt lines give the right time and then 215 trkpt lines give the wrong time.
The wrong time lies 7:10 [min:sec] before the right time:
```
<trkpt ... <time>2016-02-22T20:00:24Z</time></trkpt>
<trkpt ... <time>2016-02-22T19:53:14Z</time></trkpt>
```

Is this a bug in ITM_To_GPX.exe or does it have to do with my .itm source files?
When I convert the files with the original Qstarz software the time shift is not there.
Also in the .gpx files converted by ITM_To_GPX.exe the time suddenly 'jumps backwards' after 215 trkpt lines as in the example lines above.

The number (here 215) of trkpt lines for which this shift happens seems to be different for every file.
The offset is always 7:10.

**Comment by Eusebius1920** [comment]
I didnt make any changes to this tool in like ages...

I guess that it is most likley an error in this tool. Can you provide me an example itm file (that has this error), then I will look into it.

**Comment by sjl6** [comment]
Thanks.
Attached is an itm file including conversion by ITM_To_GPX.exe and by QTravel.
Below some example lines where the time shift occurs.
```
ITM_TO_GPX:
54 <trkpt lat="51.9940032958984" lon="4.11142110824585"><ele>34.8206939697266</ele><time>2014-02-15T11:28:05Z</time></trkpt>	--> wrong
55 <trkpt lat="51.9940032958984" lon="4.11141872406006"><ele>34.8088417053223</ele><time>2014-02-15T11:35:19Z</time></trkpt>

QTravel:
54 <trkpt lat="51.994005" lon="4.111421"><ele>34.820694</ele><time>2014-02-15T11:35:15Z</time></trkpt>
55 <trkpt lat="51.994003" lon="4.111419"><ele>34.808842</ele><time>2014-02-15T11:35:19Z</time></trkpt>

ITM_TO_GPX:
110 <trkpt lat="51.994255065918" lon="4.11082172393799"><ele>34.2761650085449</ele><time>2014-02-15T11:38:49Z</time></trkpt>
111 <trkpt lat="51.9942359924316" lon="4.11082315444946"><ele>35.0381774902344</ele><time>2014-02-15T11:31:43Z</time></trkpt>	--> wrong

QTravel:
110 <trkpt lat="51.994256" lon="4.110822"><ele>34.276165</ele><time>2014-02-15T11:38:49Z</time></trkpt>
111 <trkpt lat="51.994237" lon="4.110823"><ele>35.038177</ele><time>2014-02-15T11:38:53Z</time></trkpt>
```

[itm_gpx.zip](https://github.com/Eusebius1920/itmtogpx/files/1270614/itm_gpx.zip)

**Comment by Eusebius1920** [comment]
I think I fixed the error.

Can you confirm with v1.0.1: https://github.com/Eusebius1920/itmtogpx/releases/tag/1.0.1
?

**Comment by sjl6** [comment]
The time shift does not appear anymore. So the tool works correctly now.
Thank you very much for your fast fix!
